# Generated by Django 3.1.7 on 2021-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('iduti', models.AutoField(primary_key=True, serialize=False, verbose_name="num de l'utilisateur")),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
            ],
        ),
    ]
